version: "2.1"

services:
  jackett:
    image: linuxserver/jackett:version-v0.16.1600
#    image: julakali/jackett-source:latest
    container_name: jackett
    ports:
      - "9117:9117"
    volumes:
      - jackettconfig:/config
    environment:
      - TZ=Europe/Berlin
    restart: always
  sonarr:
    image: julakali/sonarr-bin:latest
    container_name: sonarr
    ports:
      - "8989:8989"
    restart: always
    volumes:
          - "sonarrconfig:/config"
          - /mnt/Serien:/Serien
          - /mnt/torrents:/torrents
#          - /mnt/Filme:/Filme

volumes:
  sonarrconfig:
  jackettconfig:
